import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import { roboto } from "@/font";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 
    <html lang="en" className={ roboto.className}>
      <body>
        
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
